defaults:
    - seed
    - optimizer: adam
    - scheduler: exponential
    - trainer: pl_trainer
    - callbacks: default_callbacks
    - _self_


project_name: BERT_IMDB
run_name: tucker_compression

data_params:
    data_link: imdb

model_params:
    model_link: fabriceyhc/bert-base-uncased-imdb

riemannian_params:
    is_riemann: True
    rank: [256, 256, 9]
    replace_layers_idxs: [2,]   #[2, 3, 4, 5, 6, 7, 8, 9]

training_params:
    batch_size: 56
    num_workers: 8

hydra:
  run:
    dir: plots

mlflow:
    port: '8080'

